version: '3.9'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: devenv/postgresql
    env_file:
      - docker/db/variable.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
        
  app:
    container_name: full-moon-backend
    depends_on:
      - db
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes: # マウントディレクトリ
      - ./:/go/src/app
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./docker/.go_env
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
    - "8080:8080"

volumes:
  postgresql_data: